// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial1_Ap2_Brito.DAL;

namespace Parcial1_Ap2_Brito.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200611040342_Migracion")]
    partial class Migracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Parcial1_Ap2_Brito.Models.Articulos", b =>
                {
                    b.Property<int>("articuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("costo")
                        .HasColumnType("REAL");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("existencia")
                        .HasColumnType("INTEGER");

                    b.Property<double>("valorInventario")
                        .HasColumnType("REAL");

                    b.HasKey("articuloId");

                    b.ToTable("Articulo");
                });
#pragma warning restore 612, 618
        }
    }
}
